name: FedKDD
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.10
  - pytorch >= 1.13
  - torchvision
  - pytorch-cuda=11.7
  - pip
  - pip:
    - numpy
    - argparse
    - tensorboard==2.13.0
